version: '3.7'
services:
  jenkins:
    build:
          dockerfile: ./Dockerfile
    container_name: jenkins
    ports:
     - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
